import jwt, os


key = os.getenv["SUPABASE_JWT"]
my_access_token = "eyJhbGciOiJIUzI1NiIsImtpZCI6Ijd2SU5OcFhVNTBPR0U4bXAiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL2F1Z29peGppbXltc2Fib2loeGN4LnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiI2OTc3ZDY0MS1jMGM3LTQxMjEtOTg5Yy0wYzc4MmNhMDUzZWMiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzU4MTE2ODExLCJpYXQiOjE3NTgxMTMyMTEsImVtYWlsIjoiZ2lhbm1hcmNvbW90dG9sYTAwQGdtYWlsLmNvbSIsInBob25lIjoiIiwiYXBwX21ldGFkYXRhIjp7InByb3ZpZGVyIjoiZW1haWwiLCJwcm92aWRlcnMiOlsiZW1haWwiXX0sInVzZXJfbWV0YWRhdGEiOnsiZW1haWwiOiJnaWFubWFyY29tb3R0b2xhMDBAZ21haWwuY29tIiwiZW1haWxfdmVyaWZpZWQiOnRydWUsInBob25lX3ZlcmlmaWVkIjpmYWxzZSwic3ViIjoiNjk3N2Q2NDEtYzBjNy00MTIxLTk4OWMtMGM3ODJjYTA1M2VjIn0sInJvbGUiOiJhdXRoZW50aWNhdGVkIiwiYWFsIjoiYWFsMSIsImFtciI6W3sibWV0aG9kIjoicGFzc3dvcmQiLCJ0aW1lc3RhbXAiOjE3NTgxMTMyMTF9XSwic2Vzc2lvbl9pZCI6Ijc4MTBkY2Q1LWRiN2EtNDhiYS04OTI1LWI3NWFiNjVhZDUyYSIsImlzX2Fub255bW91cyI6ZmFsc2V9.kzGb_mervLu3i2K6fLew_y5cM7URPJjDJC7izmH6IVY"
print(jwt.get_unverified_header(my_access_token))
print(jwt.decode(my_access_token, key, algorithms=["HS256"], audience="authenticated"))


# per reperire access token
# curl "https://augoixjimymsaboihxcx.supabase.co/auth/v1/token?grant_type=password" \
#   -H 'apikey: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF1Z29peGppbXltc2Fib2loeGN4Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc0OTA0NDQ4MywiZXhwIjoyMDY0NjIwNDgzfQ.VRn7qivjjw_g1ca50xKn2BNPYjvlRtwOJhWoEKYkaHM' \
#   -H 'Content-Type: application/json' \
#   -d '{"email":"gianmarcomottola00@gmail.com","password":"Gianmarco010500!"}'